spring:
  datasource:
    url: jdbc:mysql://172.27.160.1:3306/test_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: web
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 172.27.160.1
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
config:
  app:
    duration: 10000
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace